<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="gripper_effort" value="30" />
  <xacro:property name="gripper_velocity" value="0.15" />
  
  <xacro:property name="gripper_base_width" value="0.117427" />
  <xacro:property name="gripper_base_length" value="0.074326" />
  <xacro:property name="gripper_base_height" value="0.114298" />
  <xacro:property name="gripper_base_volume" value="${gripper_base_width * gripper_base_length * gripper_base_height}"/>
  <xacro:property name="gripper_base_com" value="0.024426 -0.000000 -0.000014" />

  <xacro:property name="finger_width" value="0.052970" />
  <xacro:property name="finger_length" value="0.098653" />
  <xacro:property name="finger_height" value="0.048524" />
  <xacro:property name="finger_volume" value="${finger_width * finger_length * finger_height}" />
  <xacro:property name="finger_com" value="0.025268 -0.001931 -0.000079" />

  <xacro:property name="finger_tip_width" value="0.050457" />
  <xacro:property name="finger_tip_length" value="0.102050" />
  <xacro:property name="finger_tip_height" value="0.063000" />
  <xacro:property name="finger_tip_volume" value="${finger_tip_width * finger_tip_length * finger_tip_height}" />
  <xacro:property name="finger_tip_com" value="0.027744 0.017278 0.0" />
</robot>