<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Include parallel gripper's parameters -->
  <xacro:include filename="$(find oberon7_lite)/urdf/parameters/parallel_gripper_lite.xacro" />

  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="d2r" value="0.017453293" />

  <xacro:macro name="link_box_inertial" params="mass width length height *origin">
      <inertial>
      <xacro:insert_block name="origin"/>
      <mass value="${mass}"/>
      <inertia ixx="${0.083333333 * mass * (width * width + height * height)}" ixy="0.0" ixz="0.0"
               iyy="${0.083333333 * mass * (length * length + height * height)}" iyz="0.0"
               izz="${0.083333333 * mass * (width * width + length * length)}"/>
    </inertial>
  </xacro:macro>

  <xacro:property name="base_width" value="0.198133"/>
  <xacro:property name="base_length" value="0.282087"/>
  <xacro:property name="base_height" value="0.155615"/>
  <xacro:property name="base_volume" value="${base_width * base_length * base_height}" />
  <xacro:property name="base_com" value="-0.101581 -0.001371 -0.009781"/>

  <xacro:property name="shoulder_link_width" value="0.136368"/>
  <xacro:property name="shoulder_link_length" value="0.184936"/>
  <xacro:property name="shoulder_link_height" value="0.239627"/>
  <xacro:property name="shoulder_link_volume" value="${shoulder_link_width * shoulder_link_length * shoulder_link_height}"/>
  <xacro:property name="shoulder_link_com" value="0.039670 0.005441 0.017383"/>

  <xacro:property name="upper_arm_width" value="0.141889"/>
  <xacro:property name="upper_arm_length" value="0.616809"/>
  <xacro:property name="upper_arm_height" value="0.127829"/>
  <xacro:property name="upper_arm_volume" value="${upper_arm_width * upper_arm_length * upper_arm_height}" />
  <xacro:property name="upper_arm_com" value="0.312501 0.017478 -0.000002"/>

  <xacro:property name="elbow_link_width" value="0.243672"/>
  <xacro:property name="elbow_link_length" value="0.245312"/>
  <xacro:property name="elbow_link_height" value="0.155124"/>
  <xacro:property name="elbow_link_volume" value="${elbow_link_width * elbow_link_length * elbow_link_height}" />
  <xacro:property name="elbow_link_com" value="0.125269 -0.074675 0.0"/>

  <xacro:property name="forearm_width" value="0.151455"/>
  <xacro:property name="forearm_length" value="0.151505"/>
  <xacro:property name="forearm_height" value="0.334827"/>
  <xacro:property name="forearm_volume" value="${forearm_width * forearm_length * forearm_height}" />
  <xacro:property name="forearm_com" value="0 0 ${0.5*0.31595760629823427}"/>

  <xacro:property name="wrist_width" value="0.122758"/>
  <xacro:property name="wrist_length" value="0.219204"/>
  <xacro:property name="wrist_height" value="0.130374"/>
  <xacro:property name="wrist_volume" value="${wrist_width * wrist_length * wrist_height}" />
  <xacro:property name="wrist_com" value="0.104016 0.003308 -0.000027"/>

  <!-- Inertial macros for all serial arm links  -->

  <xacro:property name="total_mass" value="0.54"/>
  <xacro:property name="total_volume" value="0.015564"/>
  <xacro:property name="total_volume_bbox" value="${base_volume + 
                                                    shoulder_link_volume +
                                                    upper_arm_volume + 
                                                    elbow_link_volume + 
                                                    forearm_volume + 
                                                    wrist_volume +
                                                    gripper_base_volume +
                                                    2 * finger_volume + 
                                                    2 * finger_tip_volume}" />

  
</robot>