rexrov:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  



  # L_j1_PC:
  #   type: effort_controllers/JointPositionController
  #   joint: oberon_L/azimuth
  #   pid: {p: 10000.0, i: 10000.0, d: 300.0}
  # L_j2_PC:
  #   type: effort_controllers/JointPositionController
  #   joint: oberon_L/shoulder
  #   pid: {p: 10000.0, i: 10000.0, d: 300.0}
  # L_j3_PC:
  #   type: effort_controllers/JointPositionController
  #   joint: oberon_L/elbow
  #   pid: {p: 10000.0, i: 10000.0, d: 300.0}
  # L_j4_PC:
  #   type: effort_controllers/JointPositionController
  #   joint: oberon_L/roll
  #   pid: {p: 10000.0, i: 10000.0, d: 300.0}
  # L_j5_PC:
  #   type: effort_controllers/JointPositionController
  #   joint: oberon_L/pitch
  #   pid: {p: 10000.0, i: 10000.0, d: 300.0}
  # L_j6_PC:
  #   type: effort_controllers/JointPositionController
  #   joint: oberon_L/wrist
  #   pid: {p: 10000.0, i: 10000.0, d: 300.0}
  L_j1_PC:
    type: effort_controllers/JointPositionController
    joint: oberon_L/azimuth
    pid: {p: 2000.0, i: 100.0, d: 50.0}
  L_j2_PC:
    type: effort_controllers/JointPositionController
    joint: oberon_L/shoulder
    pid: {p: 5000.0, i: 100.0, d: 50.0}
  L_j3_PC:
    type: effort_controllers/JointPositionController
    joint: oberon_L/elbow
    pid: {p: 2000.0, i: 100.0, d: 50.0}
  L_j4_PC:
    type: effort_controllers/JointPositionController
    joint: oberon_L/roll
    pid: {p: 1000.0, i: 50.0, d: 10.0}
  L_j5_PC:
    type: effort_controllers/JointPositionController
    joint: oberon_L/pitch
    pid: {p: 1000.0, i: 50.0, d: 10.0}
  L_j6_PC:
    type: effort_controllers/JointPositionController
    joint: oberon_L/wrist
    pid: {p: 500.0, i: 30.0, d: 10.0}


  # L_gripL_PC:
  #   type: effort_controllers/JointPositionController
  #   joint: oberon_L/finger_left_joint
  #   pid: {p: 10.0, i: 10.0, d: 0.3}
  # L_tipL_PC:
  #   type: effort_controllers/JointPositionController
  #   joint: oberon_L/finger_tip_left_joint
  #   pid: {p: 10.0, i: 10.0, d: 0.3}
  # L_gripR_PC:
  #   type: effort_controllers/JointPositionController
  #   joint: oberon_L/finger_right_joint
  #   pid: {p: 10.0, i: 10.0, d: 0.3}
  # L_tipR_PC:
  #   type: effort_controllers/JointPositionController
  #   joint: oberon_L/finger_tip_right_joint
  #   pid: {p: 10.0, i: 10.0, d: 0.3}
  L_gripL_PC:
    type: effort_controllers/JointPositionController
    joint: oberon_L/finger_left_joint
    pid: {p: 50.0, i: 0.01, d: 0.01}
  L_tipL_PC:
    type: effort_controllers/JointPositionController
    joint: oberon_L/finger_tip_left_joint
    pid: {p: 50.0, i: 0.01, d: 0.01}
  L_gripR_PC:
    type: effort_controllers/JointPositionController
    joint: oberon_L/finger_right_joint
    pid: {p: 50.0, i: 0.01, d: 0.01}
  L_tipR_PC:
    type: effort_controllers/JointPositionController
    joint: oberon_L/finger_tip_right_joint
    pid: {p: 50.0, i: 0.01, d: 0.01}







  R_j1_PC:
    type: effort_controllers/JointPositionController
    joint: oberon_R/azimuth
    pid: {p: 2000.0, i: 100.0, d: 50.0}
  R_j2_PC:
    type: effort_controllers/JointPositionController
    joint: oberon_R/shoulder
    pid: {p: 5000.0, i: 100.0, d: 50.0}
  R_j3_PC:
    type: effort_controllers/JointPositionController
    joint: oberon_R/elbow
    pid: {p: 2000.0, i: 100.0, d: 50.0}
  R_j4_PC:
    type: effort_controllers/JointPositionController
    joint: oberon_R/roll
    pid: {p: 1000.0, i: 50.0, d: 10.0}
  R_j5_PC:
    type: effort_controllers/JointPositionController
    joint: oberon_R/pitch
    pid: {p: 1000.0, i: 50.0, d: 10.0}
  R_j6_PC:
    type: effort_controllers/JointPositionController
    joint: oberon_R/wrist
    pid: {p: 500.0, i: 30.0, d: 10.0}



  # R_gripL_PC:
  #   type: effort_controllers/JointPositionController
  #   joint: oberon_R/finger_left_joint
  #   pid: {p: 10.0, i: 10.0, d: 0.3}
  # R_tipL_PC:
  #   type: effort_controllers/JointPositionController
  #   joint: oberon_R/finger_tip_left_joint
  #   pid: {p: 10.0, i: 10.0, d: 0.3}
  # R_gripR_PC:
  #   type: effort_controllers/JointPositionController
  #   joint: oberon_R/finger_right_joint
  #   pid: {p: 10.0, i: 10.0, d: 0.3}
  # R_tipR_PC:
  #   type: effort_controllers/JointPositionController
  #   joint: oberon_R/finger_tip_right_joint
  #   pid: {p: 10.0, i: 10.0, d: 0.3}
  R_gripL_PC:
    type: effort_controllers/JointPositionController
    joint: oberon_R/finger_left_joint
    pid: {p: 50.0, i: 0.01, d: 0.01}
  R_tipL_PC:
    type: effort_controllers/JointPositionController
    joint: oberon_R/finger_tip_left_joint
    pid: {p: 50.0, i: 0.01, d: 0.01}
  R_gripR_PC:
    type: effort_controllers/JointPositionController
    joint: oberon_R/finger_right_joint
    pid: {p: 50.0, i: 0.01, d: 0.01}
  R_tipR_PC:
    type: effort_controllers/JointPositionController
    joint: oberon_R/finger_tip_right_joint
    pid: {p: 50.0, i: 0.01, d: 0.01}